version: "3.8"

services:
  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_collab

    ports:
      - "5432:5432"

  server:
    build: ./server

    environment:
      JWT_SECRET: student_collab_2026_secure

    ports:
      - "5000:5000"

    depends_on:
      - db

  client:
    build: ./client

    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000

    ports:
      - "3001:3000"

    depends_on:
      - server